# Generated by Django 3.1.3 on 2021-08-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track_history", "0002_auto_20200524_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackhistoryfullsnapshot",
            name="history_data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="trackhistoryrecord",
            name="changes",
            field=models.JSONField(default=dict),
        ),
    ]
